package ru.sber.aitestplugin.ui

object UiStrings {
    const val pluginName = "Агентум"
    const val settingsTitle = "Агентум"
    const val openSettings = "Настройки"
    const val newSession = "Новая сессия"
    const val history = "История"
    const val back = "Назад"
    const val openChat = "Открыть чат"
    const val noChatsYet = "Пока нет чатов"
    const val connecting = "Подключение..."
    const val statusOffline = "не в сети"
    const val statusOnline = "подключено"
    const val statusBusy = "В работе"
    const val statusIdle = "Готов"
    const val statusRetry = "Повтор"
    const val statusWaitingApproval = "Ожидание подтверждения"
    const val statusError = "Ошибка"
    const val statusConnecting = "подключение"
    const val statusReconnecting = "переподключение"
    const val chatInputPlaceholder = "Введите запрос, / для шаблонов, # для промптов, @ для контекста"
    const val runtimeLabel = "Режим"

    const val settingsScanSection = "Сканирование шагов"
    const val settingsScanComment = "Укажите корень проекта и загрузите индекс шагов из backend-сервиса."
    const val settingsProjectRoot = "Корень проекта"
    const val settingsScanButton = "Сканировать шаги"
    const val settingsIndexedSteps = "Найденные шаги"
    const val settingsStepsEmpty = "Шаги ещё не найдены"
    const val settingsIndexMissing = "Индекс ещё не построен"
    const val settingsLoadingIndex = "Загрузка сохранённых шагов..."

    const val settingsZephyrSection = "Zephyr / Jira"
    const val settingsZephyrComment = "Настройка доступа к Jira и Zephyr для генерации и синхронизации."
    const val settingsJiraInstance = "Инстанс Jira"
    const val settingsAuthType = "Тип авторизации"
    const val settingsAuthToken = "Токен"
    const val settingsAuthLoginPassword = "Логин и пароль"
    const val settingsJiraToken = "Токен Jira"
    const val settingsLogin = "Логин"
    const val settingsPassword = "Пароль"
    const val settingsVerify = "Проверить настройки"
    const val settingsAddJiraProject = "Добавить проект Jira"
    const val settingsProjects = "Проекты Jira"

    const val settingsMemorySection = "Память проекта"
    const val settingsMemoryComment = "Правила и шаблоны, которые backend применяет при генерации."
    const val settingsOpenMemory = "Открыть управление памятью"

    const val applyFeatureTitle = "Применить feature"
    const val generateFeatureTitle = "Сгенерировать feature"
    const val dialogTargetPath = "Целевой путь"
    const val dialogTargetPathComment = "Путь относительно корня проекта."
    const val dialogCreateFile = "Создать файл, если его нет"
    const val dialogOverwriteFile = "Перезаписать существующий файл"
    const val dialogMemoryPreview = "Предпросмотр памяти"
    const val dialogRefreshPreview = "Обновить предпросмотр"
    const val dialogLoadingPreview = "Загрузка предпросмотра..."
    const val dialogPreviewUnavailable = "Предпросмотр недоступен"

    const val memoryProjectTitle = "Память проекта"
    const val memoryRulesTab = "Правила"
    const val memoryTemplatesTab = "Шаблоны"
    const val memoryRefresh = "Обновить"
    const val memoryAdd = "Добавить"
    const val memoryEdit = "Изменить"
    const val memoryDelete = "Удалить"
}
